name     : pkg-config
version  : 0.29.2
release  : 1
homePage : https://freedesktop.org/wiki/Software/pkg-config/
licence  : GPL-2.0-or-later
source   :
  uri: https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
  sha256: 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591
setup    :
  - ./configure ${CONF_OPTS}
      --disable-debug
      --disable-host-tool
      --with-internal-glib
      --with-pc-path={PK_CONFIG_PATH}
build    :
  - $make
install  :
  - $make_install

